apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: clinique
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpass
  MYSQL_DATABASE: clinique_db
  MYSQL_USER: clinic
  MYSQL_PASSWORD: clinicpass
