spring.application.name=Clinique
spring.datasource.url=jdbc:mysql://localhost:3306/clinique_DB?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.servlet.context-path=/clinique
server.port=8082
# WebSocket
spring.websocket.support=true